config/routes.rb
Rails.application.routes.draw do
  get 'designs/index'

  get 'designs/create'

  get 'services/index'

  root to: 'home#index'

  get '/company/:slug', to: 'projects#index', as: :company
  get '/company/:slug/designs/new/:id', to: 'designs#new', as: :new_design
  post '/company/:slug/designs/new/:id', to: 'designs#create'
  get '/design/download', to: 'designs#download'

  resources :users
  resources :sessions
  resources :projects
  resources :services 
end

app/models/project.rb
class Project 
  
  include Mongoid::Document

  field :name_project, type: String
	field :description, type: String
	field :e_value, type: String

  belongs_to :user
  has_many :designs, dependent: :destroy
  has_many :designers

  def company
    Rails.application.routes.url_helpers.company_url(slug: :user.slug)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  helper ProjectsHelper
  skip_before_action :verify_authenticity_token
  require 'fileutils'

  def index
    @userId =""

    if cookies[:current_session].to_s.strip.empty?
      @userId = User.find_by(slug: params[:slug])
    else
      @userId = User.find_by(_id: Rails.cache.read(cookies[:current_session]))
    end
        
    @uri = "#{request.env['HTTP_HOST'].downcase}/company/#{@userId.slug}"

    @projects = Project.where(user: @userId.id)

    respond_to do |format|
      if !@userId.to_s.strip.empty?
        format.html { render controller: "projects", action: "index" }      
        format.json { render json: @projects.to_json(), status: :ok }					
      else
        render json:{status: 'ERROR', message:'Token invalid'}, status: :unprocessable_entity
      end	
    end
  end

  def show
    @userId = User.find_by(_id: Rails.cache.read(cookies[:current_session]))
    @projects = Project.and({user: @userId.id}, {_id: params[:id]}).first

    respond_to do |format|
      if !@userId.to_s.strip.empty?    
        format.html { render controller: "projects", action: "show" }      
        format.json { render json: @projects.to_json(), status: :ok }					
      else
        render json:{status: 'ERROR', message:'Token invalid'}, status: :unprocessable_entity
      end	
    end
  end

  def new
    @userId = User.find_by(_id: Rails.cache.read(cookies[:current_session]))
  end

  def create
      @userId = User.find_by(_id: Rails.cache.read(cookies[:current_session]))
			@project = Project.create!(
				name_project: params[:name_project],
				description: params[:description],
				e_value: params[:e_value],
				user: @userId.id
			)

			respond_to do |format|
				if @project.save
					format.html { redirect_to controller: "projects", action: "index" }      
          format.json { render json: @project.to_json(), status: :created }					
				else
					format.html { render controller: "projects", action: "new" } 
					format.json { render json:{status: 'ERROR', message:'Project not saved'}, status: :unprocessable_entity }					
				end	
			end
  end

  def edit
    @project = Project.where(_id: params[:id])
  end

  def update
    @userId = User.find_by(_id: Rails.cache.read(cookies[:current_session]))
    @project = Project.where(_id: params[:id])
      .update(
        name_project: params[:name_project],
        description: params[:description],
        e_value: params[:e_value]
      )

    respond_to do |format|
      if @project
        format.html { redirect_to controller: "projects", action: "index" }      
        format.json { render json: @project.to_json(), status: :accepted }	
      else
        format.html { render controller: "projects", action: "edit" } 
        format.json { render json:{status: 'ERROR', message:'Project not saved'}, status: :unprocessable_entity }					
      end
    end		
  end

  def delete

  end 

  def destroy
    @user = User.find_by(_id: Rails.cache.read(cookies[:current_session]))
    @project = Project.and({user: @user.id}, {_id: params[:id]}).first
    @designs= Design.where(project: params[:id])
    for design in @designs do
      # Remove original designs 
      design.path_original_design.remove!
      design.save!
      
      # Remove original designs folder
      puts Rails.root
      puts design.path_original_design.url
      filePath = Rails.root + design.path_original_design.url
      parentDir = File.dirname(filePath)
      puts parentDir
      
      FileUtils.rm_rf('/home/ubuntu/P1/Proyecto1-Grupo11/public/uploads/design/path_original_design/'+design.id.to_s)
    end

    respond_to do |format|
      if !@user.to_s.strip.empty?
        @designs.delete
        @project.delete
        format.html { redirect_to controller: "projects", action: "index" }       
        format.json { render json:{status: 'SUCCES', message:'Project deleted'}, status: :ok }
      else
        format.json { render json:{status: 'ERROR', message:'Project not exist to the user'}, status: :unprocessable_entity }
      end	
    end
  end

  private

  def project_params
		params.require(:user).permit(:name_project, :description, :e_value)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
     
  def designs_list(projectId)
    stateAvailable = State.where(name_state: "Disponible").first    
    @designs = Design.collection.aggregate([
      {
        '$sort' => {'created_at' => -1}
      },
      {
        '$match' => { '$and': [{'project_id'=> projectId}, {'state_id'=> stateAvailable._id}]}
      },
      {
        '$lookup':
          {
            'from': "designers",
            'localField': "designer_id",
            'foreignField': "_id",
            'as': "designer"
          }
      },
      {
        '$lookup':
          {
            'from': "states",
            'localField': "state_id",
            'foreignField': "_id",
            'as': "state"
          }
      }
    ]).as_json()

    @designs.each do |d| 
      currentDesign = Design.where(_id: d['_id']['$oid']).first
      d['original_design'] = currentDesign.path_original_design.url
      d['mini'] = currentDesign.path_original_design.mini.url
      puts d
    end

    return @designs
  end
end

app/views/projects/edit.html.erb
<div class="container-fluid fill-height">
  <div class="row">
    <h1 class="ed-title">Modificar información</h1>
  </div>
  <div class="row">
    <div class="col-2">
    </div>
    <div class="col">
      <div class="editor border">
        <%= form_tag project_path, method: :patch do %>
          <div id="div_id_project" class="form-group required">
            <%=  label_tag 'Nombre del proyecto', nil, class:'control-label col-md-6' %><%=  text_field_tag :name_project, @name_project, class:'control-label' %><br/>
            <%=  label_tag 'Descripción', nil, class:'control-label col-md-6' %><%=  text_area_tag :description, @description, class:'control-label' %><br/>
            <%=  label_tag 'Valor estimado a pagar', nil, class:'control-label col-md-6' %><%=  text_field_tag :e_value, @e_value, class:'control-label' %><br/>
            <hr>
            <%= submit_tag 'Actualizar', class: 'control-label' %>    
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-2">
    </div>
  </div>
</div>

app/views/projects/index.html.erb
<div style="padding-top:6em;">
    <% if flash[:message] %>
        <%= show_Message %>
        <div id="messageDiv">
            <p class="messageText"><%= flash[:message] %></p>
        </div>
    <% end %>
</div>
<div>
  <h1>Mis proyectos</h1>
</div>

<div class="fill-height ">
      <!--Accordion wrapper-->
  <div class="accordion md-accordion accordion-blocks" id="accordionEx78" role="tablist"
    aria-multiselectable="true" style="padding-top: 1.5em;">
    <% if params[:slug].to_s.strip.empty? and !@userId.to_s.strip.empty? %>
      <p class="uri"> Comparte tus proyectos: <%= label_tag @uri %></p>
    <% end %>
    <% if !@projects.empty?%>
      <% @projects.each do |project| %>
        <hr>
        <!-- Accordion card -->
        <div class="card">

          <!-- Card header -->
          <div class="card-header" role="tab" id="Heading<%= project.id %>" data-toggle="collapse" href="#collapse<%= project.id %>" aria-expanded="true"
            aria-controls="collapse<%= project.id %>">

            <!--Options-->
            <% if params[:slug].to_s.strip.empty? and !@userId.to_s.strip.empty? %>
            <div class="dropdown float-left">
              <button class="btn btn-info btn-sm m-0 mr-3 p-2 dropdown-toggle" type="button" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false"><i class="fas fa-pencil-alt"></i>
              </button>
              <div class="dropdown-menu dropdown-info">
                <%= link_to 'Ver información', project_path(project), class: 'dropdown-item' %>
                <%= link_to 'Modificar', edit_project_path(project), class: 'dropdown-item' %>
                <%= link_to 'Eliminar', project_path(project), method: :delete, data: {confirm: '¿Está seguro de eliminar el proyecto?'}, class: 'dropdown-item' %>
              </div>
            </div>
            <% end %> 

            <!-- Heading -->
            <a data-toggle="collapse" href="#collapse<%= project.id %>" aria-expanded="true"
              aria-controls="collapse<%= project.id %>" >
              <h5 class="mt-1 mb-0">
                <span><%= project.name_project %></span>
                <i class="fas fa-angle-down rotate-icon"></i>              
              </h5>
            </a>

          </div>

          <!-- Card body -->
          <div id="collapse<%= project.id %>" class="collapse" role="tabpanel" aria-labelledby="Heading<%= project.id %>"
            data-parent="#accordionEx78">
            <div class="card-body">

              <% if !params[:slug].to_s.strip.empty? %>
              <%= link_to 'Subir nuevo diseño',  new_design_path(id: project.id), :method => :get, :class => "btn btn-lg bt-loadFile" %>
              <% end %> 

              <!-- Table responsive wrapper -->
              <div class="table-responsive mx-3">
                <!--Table-->
                <table class="display designsTable" style="width:100%">
                  <thead>
                    <tr>
                    <% if params[:slug].to_s.strip.empty? and !@userId.to_s.strip.empty? %>
                        <th>Nombres</th>
                        <th>Apellidos</th>
                        <th>Email</th>
                        <th>Fecha de creación</th>
                        <th>Estado</th>
                    <% end %>    
                        <th>Diseño original</th>
                    <% if params[:slug].to_s.strip.empty? and !@userId.to_s.strip.empty? %>
                        <th>Diseño convertido</th>
                        <th>Precio</th>
                    <% end %>    
                        <th>Opciones</th>
                    </tr>
                  </thead>
                  <tbody>
                    <%= render partial: '/designs/design', collection: designs_list(project.id) %>  
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
      <div class="text-muted">
        <div style="width:100%">
          <p style="text-align: center">No hay proyectos para mostrar</p>
        </div>
      </div>
    <% end %>
    <br>
    <br>
    <hr>
  </div>
  <!--/.Accordion wrapper-->
</div>				                            

app/views/projects/new.html.erb
<div class="container-fluid fill-height">
    <br>
    <div class="row">
        <div class="col-1">
        </div>
        <div class="col">
            <h1 class="ed-title">Crea tu proyecto</h1>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col-2">
        </div>
        <div class="col">
            <div class="border editor">
            <form action="/projects" method="POST">
                <div id="div_id_project" class="form-group required">
                    <label class="control-label col-md-6"><b> Nombre del proyecto: </b></label>
                    <input class="control-label" name="[name_project]">
                    
                    <label class="control-label col-md-6"><b> Descripción: </b></label>
                    <textarea class="control-label mytxt" name="[description]"></textarea>
                    <label class="control-label col-md-6"><b> Valor estimado a pagar:</b></label>
                    <input type="number" class="control-label" name="[e_value]">
                    <hr>
                    <input type="submit" class="control-label btn mybtn">                        
                </div>
            </form>
            </div>
        </div>
        <div class="col-2">
        </div>
    </div>
</div>

app/views/projects/show.html.erb
<div class="container-fluid fill-height">
  <div class="row">
    <h1 class="ed-title">Detalles</h1>
  </div>
  <div class="row">
    <div class="col-2">
    </div>
    <div class="col">
      <%= form_tag project_path, method: :patch do %>
        <div id="div_id_project" class="form-group required">
          <%=  label_tag 'Nombre del proyecto: ', nil, class:'control-label' %><%=  label_tag @projects.name_project, nil, class:'control-label' %><br/>
          <%=  label_tag 'Descripción: ', nil, class:'control-label' %><%=  label_tag @projects.description, nil, class:'control-label' %><br/>
          <%=  label_tag 'Valor estimado a pagar: ', nil, class:'control-label' %><%=  label_tag @projects.e_value, nil, class:'control-label' %><br/> 
        </div>
      <% end %>
    </div>
    <div class="col-2">
    </div>
  </div>
</div>